# generated by wodavar program
#
#
	$globals = <<'EOM';
$ADMINPASS::reserved
$ADMUSER::reserved
$AF_INET::reserved
$AT::(W) what is UNIX at program
$Action::action currently executed
$BIGICONPAR::(W) IMG tags for big icons
$CHMOD::(W) what is UNIX chmod program
$CMDLINE::are we running from command line?
$CRLF::reserved
$CRONTAB::(W) where is crontab program
$CookieGroup::reserved
$CookiePass::reserved
$DIRMODE::(W) in what mode to create directories
$DISK::(W) on WINDOS, on which drive letter is WODA related stuff 
$DUMPABLEPERL::(W) where is a dumpable version of Perl
$FILETYPES::reserved
$GREP::(W) where is grep program
$Group::current group the user belongs to
$HTMLFILE::is output going to a file
$HTTP200OK::(W) add extra HTTPD messages to please some NT servers
$Help::(i)does the user requier a lot of help in forms
$HtmlHeaderPrinted::(i)was the HTML header already printed
$ICONOPEN::reserved
$ICONPAR::(W) standard parameters for IMG tages of icons
$ICONURL::(W) URL of the icons
$INPUTOFF::reserved
$INPUTON::reserved
$InFrame::is output going into a frame
$JS::current JavaScript version supported by this browser
$LF::reserved
$MINIHEAD::reserved
$MOD_PERL::reserved
$MV::(W) where is the command to move files
$MyAction::reserved
$NOCACHE::reserved
$NOFOOT::reserved
$NO_CRYPT::Perl does not have crypt function
$NO_DIRTIMES::operating system does not show directory modification times
$NO_TIMES::Perl does not have times function
$PERL::where is Perl
$PERLV::version of Perl
$Page::name of the Page requested
$PrintingBasket::reserved
$RGroup::reserved
$Referer::reserved
$SCRIPT::URL of this script
$SENDMAIL::where is external sendmail program
$SOCK_STREAM::reserved
$SuffixDefault::reserved
$SuffixDetail::reserved
$SuffixSelf::reserved
$TESTCGIDIR::(W)directory to write generated definitions into
$TESTCGIURL::(W)URL of the above
$TMPDIR::temporary directory
$TOOLBAR1::reserved
$TOOLBAR2::reserved
$TargetDefault::reserved
$TargetDetail::reserved
$TargetParent::reserved
$TargetSelf::reserved
$ThisRecordBasket::reserved
$ThisRecordDate::data when this record was modified
$ThisRecordIcons::reserved
$ThisRecordMatches::reserved
$ThisRecordURL::URL of current record
$UNDUMP::where is undump program
$UNIX::is this a UNIX system ?
$URLGroup::group of current user as set in the URL
$URLPass::password of current user at set in the URL
$User::username of current user
$VALid::reserved
$VERSION::current version of WODA
$WBFile::name of this script
$WBHelp::URL of the WODA help files
$WBHome::home of WODA
$WBLang::lanugage of messages of this WODA
$WBLib::directory with library of subroutines
$WBPath::in which directory is this script
$WBProg::file in which is definition Perl script
$WBlanguage::language of messages in this WODA
$WBlanguageAuthor::who translated WODA to this language
EOM

	$cgis = <<'EOM';
<P><B>About</B>(user)<BR><I>   About $WBB{dbTitle}     </I>
<PRE></PRE>
<P><B>Add</B>()<BR><I>   New <!-- WBB{recordTitle} --> $WBB{recordTitle}     </I>
<PRE>
  cgiAdd
</PRE>
<P><B>AdmAgentProcess</B>(force,format,search,since,sort)<BR><I>   Processing requests   </I>
<PRE>
  admin ################################################################
</PRE>
<P><B>AdmAtNow</B>()<BR><I>  Processing of Cron Job Now Using At   </I>
<PRE></PRE>
<P><B>AdmClean</B>()<BR><I>   Cleaning the database   </I>
<PRE></PRE>
<P><B>AdmClose</B>(message)<BR><I>  Closing application to enable maintenance   </I>
<PRE></PRE>
<P><B>AdmCompile</B>()<BR><I>  'Making Compiled Version'  </I>
<PRE></PRE>
<P><B>AdmConfAttrs</B>()<BR><I>   Configurable Attributes of a WB database   </I>
<PRE></PRE>
<P><B>AdmCreate</B>(filename)<BR><I>  Structure Modification   </I>
<PRE></PRE>
<P><B>AdmCreateForm</B>(no,quick)<BR><I>   Create new Web Oriented DAtabase   </I>
<PRE></PRE>
<P><B>AdmCreateFromData</B>(IDfield,csv,dataDir,fsep,quiet)<BR><I>   Creating Database From Supplied Data   </I>
<PRE></PRE>
<P><B>AdmCreateFromDataForm</B>(quick)<BR><I>   Create WODA from CSV data   </I>
<PRE></PRE>
<P><B>AdmCronModify</B>(action)<BR><I>  Modifying Crontab Entries   </I>
<PRE></PRE>
<P><B>AdmCrons</B>()<BR><I>  Required crontab entries   </I>
<PRE></PRE>
<P><B>AdmDaily</B>()<BR><I>AdmDaily</I>
<PRE></PRE>
<P><B>AdmDelPass</B>(_id)<BR><I>  Deleting password for $id   </I>
<PRE></PRE>
<P><B>AdmDisplayStructure</B>(nolegends)<BR><I>   Structure of database $WBB{dbTitle}   </I>
<PRE></PRE>
<P><B>AdmExpire</B>(days)<BR><I>   Nothing expired   </I>
<PRE></PRE>
<P><B>AdmExpireForm</B>()<BR><I>   Delete old records from the database   </I>
<PRE></PRE>
<P><B>AdmExportCSV</B>()<BR><I>AdmExportCSV</I>
<PRE></PRE>
<P><B>AdmExportCSVS</B>()<BR><I>AdmExportCSVS</I>
<PRE></PRE>
<P><B>AdmExportID</B>()<BR><I>AdmExportID</I>
<PRE></PRE>
<P><B>AdmExportTAB</B>()<BR><I>AdmExportTAB</I>
<PRE></PRE>
<P><B>AdmExtractCat</B>(count,field)<BR><I>AdmExtractCat</I>
<PRE></PRE>
<P><B>AdmExtractCatForm</B>()<BR><I>  Extract Categories   </I>
<PRE></PRE>
<P><B>AdmImport</B>(csv,eignore,fsep,overwrite)<BR><I>   Import results   </I>
<PRE></PRE>
<P><B>AdmImportForm</B>()<BR><I>   Import .CSV file into database   </I>
<PRE></PRE>
<P><B>AdmMailForm</B>(from,message,process,search,subject,to)<BR><I>   Send serial email   </I>
<PRE></PRE>
<P><B>AdmMailSend</B>(from,message,process,search,subject,to,where)<BR><I>   Sending Serial Mail   </I>
<PRE></PRE>
<P><B>AdmMenu</B>()<BR><I>   Administration menu   </I>
<PRE></PRE>
<P><B>AdmModifyStructure</B>()<BR><I>   Edit Settings of a WODA Table   </I>
<PRE></PRE>
<P><B>AdmModifyStructureFrames</B>()<BR><I>AdmModifyStructureFrames</I>
<PRE></PRE>
<P><B>AdmModifyStructureL</B>()<BR><I>   Settings   </I>
<PRE></PRE>
<P><B>AdmOpen</B>()<BR><I>   Opened the database for general public   </I>
<PRE></PRE>
<P><B>AdmPrintCGIAPI</B>()<BR><I>   CGI functions   </I>
<PRE></PRE>
<P><B>AdmPrintPerlAPI</B>()<BR><I>   Perl functions   </I>
<PRE></PRE>
<P><B>AdmPrintVars</B>()<BR><I>   Global Variables in WODA   </I>
<PRE></PRE>
<P><B>AdmRebuildFromTab</B>()<BR><I>   Rebuilding database from tab file   </I>
<PRE></PRE>
<P><B>AdmRebuildFromTabForm</B>()<BR><I>   Rebuild database from TBL file   </I>
<PRE></PRE>
<P><B>AdmRebuildFromTabUndo</B>(action)<BR><I>   UNDO Rebuilding database from tab file   </I>
<PRE></PRE>
<P><B>AdmSetEnv</B>()<BR><I>  Storing values of some ENV variables   </I>
<PRE></PRE>
<P><B>AdmStatic</B>(_id)<BR><I>   Making static pages and indexes   </I>
<PRE></PRE>
<P><B>AdmStatus</B>()<BR><I>  'Database and WODA Status'  </I>
<PRE></PRE>
<P><B>AdvancedSearchForm</B>()<BR><I>  'Advanced Search'    </I>
<PRE></PRE>
<P><B>AgentAdd</B>(_password,_password1,_password2,email,format,search,since,sort,title)<BR><I>  Adding a job for Angie ,$cookie    </I>
<PRE>
  agent ################################################################
</PRE>
<P><B>AgentAddForm</B>(from,since)<BR><I>   Form to add a job for Angie     </I>
<PRE></PRE>
<P><B>AgentReviewChanged</B>(_password,_password1,_password2,email,rowi)<BR><I>   Changed Angie's to-do list     </I>
<PRE></PRE>
<P><B>AgentReviewForm</B>(_password,email)<BR><I>   Reviewing Angie's todo list     </I>
<PRE></PRE>
<P><B>AgentReviewWhat</B>()<BR><I>   Whose data should Angie review     </I>
<PRE></PRE>
<P><B>BasketAdd</B>(key)<BR><I>BasketAdd</I>
<PRE></PRE>
<P><B>BasketAddOne</B>(_id,num)<BR><I>BasketAddOne</I>
<PRE>
  CODE for BASEKT SUPPORT
  - BasketAdd?id=ID&num=2
  - BasketList
  - BasketEdit?id1=id1&no1=no1...
  - BasketSearch?searchParameters
  - basket file per IP number at /_basket/
  - id<TAB>number
</PRE>
<P><B>BasketEdit</B>(ri)<BR><I>BasketEdit</I>
<PRE></PRE>
<P><B>BasketShow</B>(editable,format)<BR><I>BasketShow</I>
<PRE></PRE>
<P><B>BrowseAZ</B>(how,n,name)<BR><I>  $x  </I>
<PRE></PRE>
<P><B>BrowseContents</B>(comma)<BR><I>  Browse by $f   	</I>
<PRE>
  browse contents
</PRE>
<P><B>BrowseKeywords</B>()<BR><I>  Browse by keywords in fields $f   	</I>
<PRE></PRE>
<P><B>BrowseMatrix</B>(col,row)<BR><I>  Browse Matrix by $field and $field2       </I>
<PRE></PRE>
<P><B>BrowseMatrixForm</B>()<BR><I>   Define Browse Matrix   	</I>
<PRE></PRE>
<P><B>BrowseMatrixList</B>()<BR><I>   Select Browse Matrix Combination   	</I>
<PRE></PRE>
<P><B>BrowseRing</B>(fr,id,sort,to)<BR><I>BrowseRing</I>
<PRE></PRE>
<P><B>BrowseRingToolbar</B>(fr,id,url)<BR><I>BrowseRingToolbar</I>
<PRE></PRE>
<P><B>BrowseTree</B>(field,recurse,search,separator,value)<BR><I>  $tit  </I>
<PRE>
  browse by fields in a tree
</PRE>
<P><B>Changed</B>(_dPassword,_id,_password,_password1)<BR><I>   Confirm Edits ,$x    </I>
<PRE></PRE>
<P><B>Debug</B>(x)<BR><I>  Useful Data for Debuging and Troubleshooting   </I>
<PRE></PRE>
<P><B>Delete</B>(_id)<BR><I>   Delete record $CGI{_id}     </I>
<PRE></PRE>
<P><B>DeleteIt</B>(_dPassword,to)<BR><I>  Delete results     </I>
<PRE></PRE>
<P><B>DisplayStructure</B>()<BR><I>   Information about fields in $WBB{dbTitle}    </I>
<PRE></PRE>
<P><B>Edit</B>(_id)<BR><I>   Edit record $CGI{_id}     </I>
<PRE></PRE>
<P><B>EditForm</B>(_dPassword,_id)<BR><I>   Edit $id     </I>
<PRE></PRE>
<P><B>Go</B>(_id,search,sort,to)<BR><I>   No such record $i   </I>
<PRE></PRE>
<P><B>HelpSearch</B>()<BR><I>   Search Tips   	</I>
<PRE></PRE>
<P><B>Home</B>()<BR><I>   Home Page     </I>
<PRE></PRE>
<P><B>Login</B>(groupname,password,referer,win)<BR><I>  $t\n ,$cookie  </I>
<PRE></PRE>
<P><B>LoginForm</B>(groupname,referer,win)<BR><I> $t   </I>
<PRE></PRE>
<P><B>NewForm</B>()<BR><I>   News Form     </I>
<PRE></PRE>
<P><B>Param</B>(x)<BR><I>   Cgi parameters   </I>
<PRE></PRE>
<P><B>Query</B>()<BR><I>Query</I>
<PRE></PRE>
<P><B>ResetCookie</B>(cookie,referer)<BR><I>ResetCookie</I>
<PRE></PRE>
<P><B>Search</B>(cookie,days,ei,fi,first,format,frames,grouping,max,search,since,sort,vi,xx)<BR><I>   Search Results ,$cookie    </I>
<PRE>
  USES:
  	CGI{search}	... what
  	CGI{sort}	... DEFAULT, TIME, sort1, sort2 ...
  	CGI{format}	... DEFAULT, LONG, format1, format2 ...
 	CGI{first}	... 0
 	CGI{max}	... 20
 	CGI{days}	... younger than x days
 	CGI{noshit}	... nothing but results
</PRE>
<P><B>SearchAgain</B>()<BR><I>  Search again in recent $n searches    </I>
<PRE></PRE>
<P><B>SearchForm</B>(search)<BR><I>  Simple search form   </I>
<PRE></PRE>
<P><B>SearchIDForm</B>()<BR><I>   Search by record ID     </I>
<PRE></PRE>
<P><B>SetHelp</B>(help,referer)<BR><I>SetHelp</I>
<PRE></PRE>
<P><B>Show</B>(_id,sort)<BR><I>   </I>
<PRE></PRE>
<P><B>Store</B>(files,from,to)<BR><I>   Store   </I>
<PRE></PRE>
<P><B>Toc</B>()<BR><I>   Table of Contents     </I>
<PRE>
  display table of contents
</PRE>
<P><B>Undo</B>(file)<BR><I>   Undo changes     </I>
<PRE></PRE>
EOM

	$xxxs = <<'EOM';
<P><B>FETCH ($url)</B>
<PRE>
  fetches $url and returns the part of page
  between A NAME=PAGEBODYN tags
  or whole page if that is not found

  this function may not work on some
  windows httpd servers (IIE, Xitami)
</PRE>
<P><B>FLD ($table,$id,$name)</B>
<PRE>
  get a value of field $name of record $id fromt table $table
  $tabe must be defined in $WBB{tables}
</PRE>
<P><B>ID ($string)</B>
<PRE>
  modifies $string so that it can be used
  as a record ID e.g. replaces does with undercsores
</PRE>
<P><B>KEY ($table,$id)</B>
<PRE>
  is there a record with id=$id in
  table $table ?
</PRE>
<P><B>NOOP()</B>
<PRE>
  does nothing at all
</PRE>
<P><B>PIC()</B>
<PRE>
  formats values in %rec hash into %pic hash
  using instructions in $WBB{afield,picture} 
</PRE>
<P><B>QRY ($table,$search,$then,$sort,$format,$first,$max,$flds) </B>
<PRE>
  Performs a search in table $table
  and returns results formatted in HTML
  parameters correspond to CGI parameters
  of standard or advanced search

  Fails on some Windows Web servers such as IIE
  that don't let you call another Perl program.

  Run Debug info from Admin menu to check if it
  has a chance of working. 
</PRE>
<P><B>ROWS($table,$flds,$search,$then,$sort,$format,$first,$max)</B>
<PRE>
  get raw data (tab separated) from $table
  similar to QRY function with $format=RAW
  $flds are comma separated field names
</PRE>
<P><B>TODAY()</B>
<PRE>
  returns today's date formatted in a way
  proper for Woda date fields
</PRE>
EOM

1;
